# Generated by Django 3.2.3 on 2021-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occuped',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
