# Generated by Django 3.2.3 on 2021-05-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
