# Generated by Django 3.2.3 on 2021-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.AddField(
            model_name='file',
            name='newEdition',
            field=models.BooleanField(default=False),
        ),
    ]
