# Generated by Django 3.2.3 on 2021-06-01 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210601_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
