# Generated by Django 3.0.8 on 2021-07-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='newEdition',
        ),
    ]
